# --- Kredensial Login Aplikasi ---
ADMIN_PASSWORD = "admin123"
OPERATOR_PASSWORD = "operator123"

# --- Kredensial Google Sheets ---
spreadsheet_id = "1dkVpBTIyj0sJAh8gbtOqe3rfYQD8cFOWxUlepb1lgZM"

[gcp_service_account]
type = "service_account"
project_id = "pantau-kandang-sapi"
private_key_id = "2ce9cd20e6d533308dfc9854ee37aa66bfa7e363"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDpuPds+1odTbHN\nPYO8jnD/RN59sdxVs6DCmJOeujxA8Sy40RsIZdGjFSmoYTWU+lf/o1UDWOawCsvv\nFnLA+/Xf+l87ZScVIIqiquTATINmkec6OtU7WzrEBeZXRF7WZ57Sw49U0lofso/e\nsO7jItxD1+re0AhOAObl5zAT8rvcFYCo1GQ93IX1I/PPv8RwcM5qYM40ck3cpQrT\nDm3embBn0J/Nh9ZtTX6ZSQqGGtRKOJX+Ky9Rcumztsd/RwDsQh6wC8IklGp0O9+G\n8q7RA4yY4OCzl1UzHttn6q/gU5N3fZt4mlN99TvWZN4kPEKExVjy+LQw1U8kYK++\nROVzZWqBAgMBAAECggEABU9nh7laPcozHPel05Xk6VfWOkLdP7E6GNHAoN2YWt1f\n578QfytZDPyBGstCnWTmtO8wEkhlzWAhbAg1iT7wQit9GGte7PL1U2bQlbHnVmBA\nQaluiM+00RlVN2xdPz/RcvZwfjvdQlUbQbMBanWzTXNNacyOM79/f3+2Lu3X6NMl\nH3wFt2eyEi2gJF5Ptty48s3ENZNwChxtRqm+xaAK0tzqv8NIcmF/yaL37nboHQ9H\ncesd0NKS/GgCs3D/TuceU/lt9MD0HBUf+AvrCfSAPvEwiYSRvriLRHjNdsJSVbGY\nRkUdAnuP2MwtgxdYSA+RqeteqvGPZiYHscFBXfQgFQKBgQD76AK48DoWRFBODugD\nGFGO+4fierqzCO6Kay2gG9iv2wRJD42kFirFy6tS624G3o9n8hk0ve04TICQcun5\n9ODQzfGu7Rmga7iLK0AUcG3DEly1ur6zAuCS4PEurGiMC69JwrUiuVoPB9cj90Oj\nwP0OBh/8DDg0oxRMMCRDOVpj+wKBgQDthU6gOfbFVRHUhMMcF5L8znzv9vvtFf8p\nDRjG/e3MTOLBkGk5yoIc13U3cZy2u14h+m/lnJE+uxzsWqRrj6Js0G9c8S1F/JwU\nByD3PWtJXQHDsaZisoO+d302UVrEBd10Sou9eWAlsi5tGx2FP/CSMOyP261gs5lw\nfJl6TbrmswKBgQCnVDVCvagIFHa3cyVgsO20KZbYtSeBN4Skg486FGU6YySUl3VB\nssvUuXZjTSm3/GyL4oAlzadex0p7KSoMtEIF0VciGDL2obdjEmatbQUsF+1nddWo\nuVeNmUf79eA4bqaQO3rwxuhwpYeeR2gxxUcS4rSqSz+mj1EzTqM32EgXswKBgHUL\nVvZ/+cm+JP4ruhXSzB0GB+0cMYLgbw+ko4wTv6YIUUl/R0syLrHVvq5mrwohBL8L\nsS5d2/kkrZkPBaz3Z9vlTqtnMZ8mXydDaAxN2NubGG590Xcbbu5h5XLp3idwmHNg\n9MGW2TlaN6SOUxrBqmPv9fLiFurrNfaHf/4T5cEfAoGADQ7mgl9935axhLyVbvge\nfuwFulVK1NdAEa7GaKJlp/hGUZIxz+ggzFUP4pLnLE0rDCScXua8K6Dl1OBgl1RE\nF52/fpGBTIF5NJnnWYXwkxfmX1uM7OnI/95mZfE3PyrA9cxEi/JM4WOzvP9h1FVB\n4FRYfdcEmYe9fbnNn+MDjig=\n-----END PRIVATE KEY-----\n"
client_email = "pantau-kandang-sapi@pantau-kandang-sapi.iam.gserviceaccount.com"
client_id = "117107999337173763550"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/pantau-kandang-sapi%40pantau-kandang-sapi.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# --- Kredensial Database Supabase (Connection Pooler IPv4) ---
[supabase]
connection_string = "postgresql://postgres.xputzryhkpmqdbwvtlsy:%40Riyan170887@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres"
host = "aws-0-ap-southeast-1.pooler.supabase.com"
user = "postgres.xputzryhkpmqdbwvtlsy"
password = "@Riyan170887"
port = 6543
database = "postgres"